### ISSUE TITLE
Support for SMOS40 + S2125

### ISSUE THREAD

**Issue by cybermaus** [yozik04/nibe#32]
The new HA version made me aware of this project.
At this moment, I am directly using the modbus integration to get some values, but this one seems very promising.
But alas, I cannot use the official integration, because I have a newer S series, and tcp/modbus.

Which seems to be listed here as experimental. Great.

I see some install instructions for Docker and PyPi, but not for HA OS.
Can anyone give me some pointers on how to install and try this?

**Comment by yozik04** [comment]
@elupus I have some CSV data for you in English =)

**Comment by nkrepo** [comment]
Hi all,
I have the SMOS40 controller connected  with F21210 heat-pump.
I am attaching the the Modbus registers dumped from the SMOS40 controller with firmware Version 2.14.8.

As I can understand through the Modbus of SMOS40 controller the registers from F21210 heat-pump can be accessed also.

[smos40_modbus_addresses_all_20221016-06765422020001-1_firmware_2.14.8.csv](https://github.com/yozik04/nibe/files/9794245/smos40_modbus_addresses_all_20221016-06765422020001-1_firmware_2.14.8.csv)

**Comment by cybermaus** [comment]
If you are using Home Assistant, pending the completion of this project, (and assuming you know how to modify the yaml configuration) you can use this example to get out some values into your HA.
([which I copied and modified from here](https://community.home-assistant.io/t/modbus-configuration-for-nibe-s-series-heatpumps/400422/4))

```
modbus:
   - name: "Nibe2125"
     type: tcp
#    host: 192.168.x.x # over WiFi
     host: 192.168.x.x # over Eth
     port: 502
     
     sensors:
#Priority	MODBUS_INPUT_REGISTER	1028	1		4	0	0	0
        - name: "WP Operating Prioritisation"
          unique_id: "wp_operating_prioritisation"
          data_type: int16  # int8
          # 10: Off, 20: Hot Water, 30: Heat, 40: Pool, 50: Cooling
          address: 1028
          input_type: input  # R/W
          scale: 1
          precision: 0
          state_class: measurement
          slave: 1
        - name: "WP Outdoortemperatur (BT1)"
          unique_id: "wp_outdoor_temp_bt1" 
          device_class: temperature
          unit_of_measurement: "°C"
          data_type: int16
          state_class: measurement
          address: 1
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 0.1
          scan_interval: 60
        - name: "WP AVG Outdoortemperatur (BT1)"
          unique_id: "wp_avg_outdoor_temp_bt1" 
          device_class: temperature
          unit_of_measurement: "°C"
          data_type: int16
          state_class: measurement
          address: 37
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 0.1
          scan_interval: 60
#Roomsensor 1-1	MODBUS_INPUT_REGISTER	26	10	°C	2	0	0	0
        - name: "WP Room temperature 1 (BT50)"
          unique_id: "wp_room_temp_bt50"
          device_class: temperature
          unit_of_measurement: "°C"
          data_type: int16
          state_class: measurement
          address: 26
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 0.1
          scan_interval: 60
#Room average temp. clim. system 1 (BT50)	MODBUS_INPUT_REGISTER	116	10	°C	2	0	0	0
#RMU is 2*AVG-BT1 (or rather, AVG=(BTU+RMU)/2
        - name: "WP Room temperature 2 (RMU1)"
          unique_id: "wp_room_temp_rmu"
          device_class: temperature
          unit_of_measurement: "°C"
          data_type: int16
          state_class: measurement
          address: 116
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 0.1
          scan_interval: 60

          # To be categorised
        - name: "WP Externe cv-pomp status"
          unique_id: "wp_externe_cv-pomp_status"
          data_type: int16  # uint8
          address: 1066
          input_type: input
          scale: 1
          precision: 0
          state_class: measurement
          slave: 1
        - name: "wp Active Alarm"
          unique_id: "wp_active_alarm"
          data_type: int16  # uint8
          address: 2195
          input_type: input
          scale: 1
          precision: 0
          state_class: measurement
          slave: 1
        - name: "WP Alarm Number"
          unique_id: "wp_alarm_number"
          data_type: int16  # uint16
          address: 1975
          input_type: input
          scale: 1
          precision: 0
          state_class: measurement
          slave: 1    
#Supply line (EB101-BT12)	MODBUS_INPUT_REGISTER	1478	10	°C	2	0	0	0
        - name: "WP Supply Line Temperature (BT12)"  # BT12
          unique_id: "wp_supply_line_temperature_bt12"
          unit_of_measurement: "°C"
          data_type: int16
          device_class: temperature
          address: 1478
          input_type: input  # R
          scale: 0.1
          precision: 1
          state_class: measurement
          slave: 1
#Return line (EB101-BT3)	MODBUS_INPUT_REGISTER	1475	10	°C	2	0	0	0
        - name: "WP Return Line Temperature (BT3)"  # BT3
          unique_id: "wp_return_line_temperature_bt3"
          unit_of_measurement: "°C"
          data_type: int16
          device_class: temperature
          address: 1475
          input_type: input  # R
          scale: 0.1
          precision: 1
          state_class: measurement
          slave: 1
        - name: "WP Hot water charging (BT6)"
          unique_id: "wp_hot_water_charging_bt6"
          device_class: temperature
          unit_of_measurement: "°C"
          data_type: int16
          state_class: measurement
          address: 9
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 0.1
          scan_interval: 60
        - name: "WP Hot water display (BT7)"
          unique_id: "wp_hot_water_display_bt7"
          device_class: temperature
          unit_of_measurement: "°C"
          data_type: int16
          state_class: measurement
          address: 8
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 0.1
          scan_interval: 60        
        - name: "WP External supply line (BT25)"
          unique_id: "wp_external_supply_line_bt25"
          device_class: temperature
          unit_of_measurement: "°C"
          data_type: int16
          state_class: measurement
          address: 39
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 0.1
          scan_interval: 60
        - name: "WP Return temperature (BT71)"
          unique_id: "wp_return_temp_bt71"
          device_class: temperature
          unit_of_measurement: "°C"
          data_type: int16
          state_class: measurement
          address: 88
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 0.1
          scan_interval: 60    


#Compressor status (EB101)	MODBUS_INPUT_REGISTER	1484	1		4	0	0	0
        - name: "WP Compressor Status"
          unique_id: "wp_compressor_status"
          data_type: int16 # uint8
          # 0: Off, 1: On (Operate)
          address: 1484
          input_type: input # R
          scale: 1
          precision: 0
          state_class: measurement
          slave: 1
#Huidige compres­sorfre­quentie (EB101)	MODBUS_INPUT_REGISTER	**1803**	10	Hz	2	0	0	0
        - name: "WP Compressor speed"
          unique_id: "wp_compressor_speed"
          device_class: frequency
          unit_of_measurement: "Hz"
          data_type: int16
          state_class: measurement
          address: 1803
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 0.1
          scan_interval: 60
#Compressor, time to start (EB101-EP14)	MODBUS_INPUT_REGISTER	1485	1	min	4	0	0	0
        - name: "WP Compressor time to start"
          unique_id: "wp_compressor_time_to_start"
          device_class: duration
          unit_of_measurement: "minutes"
          data_type: int16
          state_class: measurement
          address: 1485
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 1
          scan_interval: 60
#Evaporator (EB101-BT16)	MODBUS_INPUT_REGISTER	1622	10	°C	2	0	0	0
##Evaporator 2 (EB101-EP14-BT16)	MODBUS_INPUT_REGISTER	1966	10	°C	2	0	0	0
        - name: "WP Evaporator Temperature (BT16)"  # BT16
          unique_id: "wp_evaporator_temperature_bt16"
          unit_of_measurement: "°C"
          data_type: int16
          device_class: temperature
          address: 1622
          input_type: input  # R
          scale: 0.1
          precision: 1
          state_class: measurement
          slave: 1
#Outdoor temperature (EB101-BT28)	MODBUS_INPUT_REGISTER	1621	10	°C	2	0	0	0
        - name: "WP Outdoor temperature (BT28)"  # BT16
          unique_id: "wp_outdoor_temperature_bt28"
          unit_of_measurement: "°C"
          data_type: int16
          device_class: temperature
          address: 1621
          input_type: input  # R
          scale: 0.1
          precision: 1
          state_class: measurement
          slave: 1
#Fan speed (EB101)	MODBUS_INPUT_REGISTER	401	1	rpm	5	0	0	0
        - name: "WP Fan speed"
          unique_id: "wp_fan_speed"
          device_class: speed
          unit_of_measurement: "rpm"
          data_type: int16
          state_class: measurement
          address: 401
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 1
          scan_interval: 60

#Heating medium pump speed (GP1)	MODBUS_INPUT_REGISTER	1636	1	%	4	0	0	0
        - name: "WP Speed loadpump (GP12.1)"
          unique_id: "wp_speed_loadpump1"
          device_class: speed
          unit_of_measurement: "%"
          data_type: int16
          state_class: measurement
          address: 1636
          count: 1
          slave: 1
          precision: 1
          input_type: input
          scale: 1
          scan_interval: 60

        - name: "WP AUX11 Active Heating"
          unique_id: "wp_aux11"
          data_type: int16
          address: 224
          input_type: input
          state_class: measurement
          scan_interval: 60
```
